#################################################################################
# Copyright 2018 Dell Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#
# @author: Tingyu Zeng, Dell
# @version: 0.1.0
#################################################################################

# This is a TOML config file for edgexsecurity service.

title = "EdgeX security service config file"

[kongurl]
server = "localhost"
adminport = "8001"
applicationport = "8000"

[kongadmin]
username = "administrator"
password = "changeme"

[secretservice]
server = "127.0.0.1"
port = "8200"
healthcheckpath = "v1/sys/health"
certpath = "v1/secret/edgex/cert"
token = "232d6e0a-3a09-1090-aa08-b303f28c05e1"
snis = "edgex.com"

[edgexservices]
	[edgexservices.coredata]
		name = "coredata"
		host = "localhost"
		port = "48080"
		protocol = "http"
	
	[edgexservices.metadata]
		name = "metadata"
		host = "localhost"
		port = "48081"
		protocol = "http"
	
	[edgexservices.command]
		name = "command"
		host = "localhost"
		port = "48082"
		protocol = "http"
	
	[edgexservices.notifcations]
		name = "notifications"
		host = "localhost"
		port = "48060"
		protocol = "http"
		
